- hosts: localhost
  connection: local

vars:

########################################################## You may change any of these variables.


    AZURE_SUBSCRIPTION_ID: "0f583d45-a241-496e-87f3-ba1e66a16b9e"
    sp_client_id: "96430035-c0c3-4deb-862b-4ffc309e7a04"
    sp_secret: "Nku8Q~k29VD5QnWMlFbNK6qDfxJUMRzBbjTdKcPB"
    aro_master_subnet: "AROMasterSubnet"
    aro_master_subnet_cidr: "100.100.10.0/24"
    aro_vnet: "AROVNet"
    aro_vnet_cidr: "100.100.0.0/16"
    aro_worker_subnet: "AROWorkerSubnet"
    aro_worker_subnet_cidr: "100.100.20.0/24"
    azure_dc: "westeurope"
    cluster_name: "aro4prd"
    pull_secret: "{{ lookup('file', 'pull-secret.txt') }}"
    customdns: "arolabprd.lab.kubesupport.com"
    version: "4.12.25"
    master_vm_size: "Standard_D8s_v3"
    network_pod_cidr: "10.128.0.0/16"
    network_service_cidr: "10.129.0.0/16"
    privacy_api: "Public"
    privacy_ingress: "Public"
    resource_group: "aro-lab-prd"
    worker_node_count: "4"
    worker_vm_size: "Standard_D4s_v3"
  tasks:
    - name: Create openshift cluster
      azure_rm_openshiftmanagedcluster:
        resource_group: "{{ resource_group }}"
        name: "{{ cluster_name  }}"
        location: {{ azure_dc }}
        state: absent
